# Generated by Django 3.2.9 on 2022-03-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('czyKierownik', models.BooleanField(default=False)),
                ('czyAdministrator', models.BooleanField(default=False)),
                ('mail', models.CharField(max_length=45)),
                ('haslo', models.CharField(default='RUwpBlZAVfkq', max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Pracownicy',
            },
        ),
    ]
