# Generated by Django 4.0.3 on 2022-03-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaFirmy', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Firmy',
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('czyKierownik', models.BooleanField(default=False)),
                ('czyAdministrator', models.BooleanField(default=False)),
                ('mail', models.CharField(max_length=45)),
                ('haslo', models.CharField(default='nnueZzOGdxkk', max_length=12)),
                ('firma', models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, related_name='firma', to='demo.firma')),
            ],
            options={
                'verbose_name_plural': 'Pracownicy',
            },
        ),
    ]
