# Generated by Django 4.0.3 on 2022-03-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zlecajacy', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Prace',
            },
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='haslo',
            field=models.CharField(default='jsGTHsjrVwDm', max_length=12),
        ),
    ]
