# Generated by Django 4.0.3 on 2022-03-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='haslo',
            field=models.CharField(default='BMEWmEyirxVO', max_length=12),
        ),
    ]
