# Generated by Django 4.0.3 on 2022-03-30 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praca',
            name='idPracownika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='haslo',
            field=models.CharField(default='wWgSdLklaIfw', max_length=12),
        ),
        migrations.AlterField(
            model_name='zapispracy',
            name='idPracownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
