# Generated by Django 4.0.3 on 2022-03-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='nazwaFirmy',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='haslo',
            field=models.CharField(default='KldKayBPXzCi', max_length=12),
        ),
    ]
