# Generated by Django 4.0.3 on 2022-03-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_firma_nazwafirmy_alter_pracownik_haslo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='haslo',
            field=models.CharField(default='jsNFhMKSQEfO', max_length=12),
        ),
    ]
